name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Varnish Cache
        run: |
          curl -s https://packagecloud.io/install/repositories/varnishcache/varnish73/script.deb.sh | sudo bash
          sudo apt-get install varnish-dev

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run clippy
        run: cargo clippy --all-targets --all-features

  run-fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check

  run-tests:
    strategy:
      fail-fast: false
      matrix:
        unleash-version:
          - v4
          - v5
          - v6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Unleash
        run: docker compose -f ./docker/docker-compose.yml -f ./docker/${{ matrix.unleash-version }}/docker-compose.yml up  -d

      - name: Setup Varnish Cache
        run: |
          curl -s https://packagecloud.io/install/repositories/varnishcache/varnish73/script.deb.sh | sudo bash
          sudo apt-get install varnish-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build all targets
        run: cargo build --all-targets

      - name: Run tests
        run: cargo test --all-targets
