name: Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v2
        env:
          OUTPUT: CHANGELOG.md
        with:
          args: --tag ${{ inputs.version }}

      - name: Install cargo set-version
        run: cargo install cargo-edit --no-default-features --features="set-version"

      - name: Set package's version
        env:
          VERSION: ${{ inputs.version }}
        run: cargo set-version ${VERSION//v}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore(release): prepare for ${{ inputs.version }}'
          title: 'chore(release): prepare for ${{ inputs.version }}'
          body: This PR was opened by the [Release PR](https://github.com/teqm/libvmod-unleash/actions/workflows/release-pr.yml) GitHub workflow. When you're ready to do a release, you can merge this and create matching tag - the package will be released automatically.
          branch: release-pr
