name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    outputs:
      release-body: ${{ steps.changelog.outputs.content }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v2
        id: changelog
        with:
          args: --latest --strip header

  release:
    needs: [generate-changelog]
    strategy:
      matrix:
        include:
          - pkg: deb
            platform: linux/amd64
          - pkg: deb
            platform: linux/arm64
          - pkg: rpm
            platform: linux/amd64
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ matrix.platform }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          file: ./pkg/${{ matrix.pkg }}/Dockerfile
          load: true
          tags: libvmod-unleash:latest

      - name: Copy release artifacts
        env:
          PLATFORM: ${{ matrix.platform }}
          GIT_TAG: ${{ github.ref_name }}
        run: |
          VMOD_VERSION=${GIT_TAG//v}
          ARCH=${PLATFORM//linux\/}
          
          docker create -it --name libvmod-unleash libvmod-unleash:latest
          
          if [ "${{ matrix.pkg }}" = "deb" ]; then
            docker cp libvmod-unleash:/tmp/libvmod-unleash/target/debian/vmod-unleash_$VMOD_VERSION_$ARCH.deb .
          else
            docker cp libvmod-unleash:/root/rpmbuild/RPMS/x86_64/vmod-unleash-$VMOD_VERSION-1.el7.x86_64.rpm .
          fi

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ needs.generate-changelog.outputs.release-body }}
          files: |
            vmod-unleash*.rpm
            vmod-unleash*.deb
